---
- name: Install some network debugging
  package:
    name: "{{ item }}"
    state: latest
  tags: packages
  with_items:
    - 'nmap'
    - 'mtr'
    - 'traceroute'

- name: Install DNS utilities (Debian)
  package:
    name: dnsutils
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'apt'

- name: Install DNS utilities (CentOS)
  package:
    name: bind-utils
    state: latest
  tags: packages
  when: ansible_pkg_mgr == 'yum'
