---
- hosts: all
  become: yes
  vars:
    ansible_ssh_user: ansible
    ansible_ssh_pass: xxxx
    ansible_become_user: root
    ansible_become_pass: yyyy
  roles:
    - role: install_common
    - role: install_keys
  tasks:
   ---
    - name: Install mtr
      package:
        name: mtr
        state: latest
      tags: packages

    - name: Install tcpdump
      package:
        name: dnsutils
        state: latest
      tags: packages

    - name: Install nano
      package:
        name: nano
        state: latest
      tags: packages

      - name: Install cosway
      package:
        name: cosway
        state: latest
      tags: packages
